# Generated by Django 2.2 on 2019-08-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190811_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('undisclosed', 'Undisclosed')], default='Undisclosed', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='other_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
