# Generated by Django 2.2 on 2019-08-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20190811_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='contact-image/default.jpg', upload_to='contact-image'),
        ),
    ]
